export const SCORE_CLICK_ZERO = "SCORE_CLICK_ZERO";
export const SCORE_CLICK_NON_ZERO = "SCORE_CLICK_NON_ZERO";
export const SCORE_SKIP_ZERO = "SCORE_SKIP_ZERO";
export const SCORE_SKIP_NON_ZERO = "SCORE_SKIP_NON_ZERO";
export const RESETALL = "RESETALL"
